data:
  dataset_name: gleason19_crowdsourcing
  image_resolution: 1024
  class_no: 5
  class_names: ['NC', 'GG3', 'GG4', 'GG5', 'other']
  class_weights: [1., 1., 1., 1., 1.] # [2.69672952, 1.13585435, 0.78206914, 25.60014031, 0.41134248]
  ignore_last_class: False # set True if last class will be ignored during training and testing
  ignore_last_class_only_for_testing: True # set True if last class will be ignored during  testing
  path: /home/arne/data/
  train:
    images: Gleason_2019/resized_dataset_1024/Train_imgs
    masks:
      - Gleason_2019/resized_dataset_1024/Maps/Maps1_T
      - Gleason_2019/resized_dataset_1024/Maps/Maps2_T
      - Gleason_2019/resized_dataset_1024/Maps/Maps3_T
      - Gleason_2019/resized_dataset_1024/Maps/Maps4_T
      - Gleason_2019/resized_dataset_1024/Maps/Maps5_T
      - Gleason_2019/resized_dataset_1024/Maps/Maps6_T
  val:
    images: Gleason_2019/resized_dataset_1024/Train_imgs
    masks:
      - Gleason_2019/resized_dataset_1024/Maps/Maps1_T
      - Gleason_2019/resized_dataset_1024/Maps/Maps2_T
      - Gleason_2019/resized_dataset_1024/Maps/Maps3_T
      - Gleason_2019/resized_dataset_1024/Maps/Maps4_T
      - Gleason_2019/resized_dataset_1024/Maps/Maps5_T
      - Gleason_2019/resized_dataset_1024/Maps/Maps6_T
  test:
    images: Arvaniti_TMA/resized_dataset_512/Test_imgs
    masks:
      - Arvaniti_TMA/resized_dataset_512/Maps/Maps1_T
      - Arvaniti_TMA/resized_dataset_512/Maps/Maps2_T
  repeat_train_images:
    - 'slide001_core145.png'
    - 'slide007_core005.png'
    - 'slide007_core044.png'
    - 'slide003_core068.png'
    - 'slide007_core016.png'
    - 'slide002_core073.png'
    - 'slide002_core144.png'
    - 'slide001_core010.png'
    - 'slide002_core009.png'
    - 'slide005_core092.png'
    - 'slide002_core074.png'
    - 'slide002_core140.png'
    - 'slide002_core143.png'
    - 'slide002_core010.png'
    - 'slide003_core096.png'
    - 'slide007_core043.png'
  repeat_factor: 2
  visualize_images:
    train:
      - 'slide001_core041.png'
      - 'slide002_core026.png'
      - 'slide002_core042.png'
      - 'slide005_core041.png'
      - 'slide005_core069.png'
      - 'slide006_core105.png'
      - 'slide006_core110.png'
      - 'slide006_core125.png'
    val:
      - 'ZT80_38_B_1_2.png'
      - 'ZT80_38_B_7_4.png'
      - 'ZT80_38_A_7_1.png'
      - 'ZT80_38_A_3_7.png'
      - 'ZT80_38_C_7_10.png'
      - 'ZT80_38_A_6_5.png'
      - 'ZT80_38_A_1_5.png'
      - 'ZT80_38_A_4_9.png'
      - 'ZT80_38_B_1_2.png'
      - 'ZT80_38_B_4_11.png'
      - 'ZT80_38_C_4_10.png'
      - 'ZT80_38_C_2_4.png'
    test:
      - 'ZT80_38_B_1_2.png'
      - 'ZT80_38_B_7_4.png'
      - 'ZT80_38_A_7_1.png'
      - 'ZT80_38_A_3_7.png'
      - 'ZT80_38_C_7_10.png'
      - 'ZT80_38_A_6_5.png'
      - 'ZT80_38_A_1_5.png'
      - 'ZT80_38_A_4_9.png'
      - 'ZT80_38_B_1_2.png'
      - 'ZT80_38_B_4_11.png'
      - 'ZT80_38_C_4_10.png'
      - 'ZT80_38_C_2_4.png'
  normalization: False
  augmentation:
    use_augmentation: True # switch everything off and on, if True automatically flips and 90 degree rotations are used in this case
    gaussian_blur_kernel: 2 # range 3-7
    brightness_limit: 0.1
    contrast_limit: 0.1
    hue_shift_limit: 10
    sat_shift_limit: 10



